name: "\U0001F41B Bug Report"
title: "[Bug]: " 
labels: bug
assignees: octocat

body:
- type: input
  id: joplin-version
  attributes:
    label: Joplin version
    description: The version of Joplin you are using.
    placeholder: ex. 2.6.10
    value: ""
  validations:
    required: true

- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: The platform you are using Joplin on.
    options:
      - macOS
      - Linux
      - Windows
      - Android
      - iOS
      - terminal
    value: ""
  validations:
    required: true

- type: input
  id: os-specifics
  attributes:
    label: OS specifics
    description: The OS version, Linux distribution, Android/iOS version, etc.
    placeholder: ex. Windows 10, Ubuntu 20.04, Android 11
    value: ""
  validations:
    required: true

- type: dropdown
  id: sync-target
  attributes:
    label: Sync target
    description: The service you are using to sync your notes.
    options:
      - Dropbox
      - OneDrive
      - Nextcloud
      - WebDAV
      - File system
      - Joplin Server
    value: ""
  validations:
    required: true

- type: dropdown
  id: encryption-method
  attributes:
    label: Encryption method
    description: The method you are using to encrypt your notes.
    options:
      - E2EE
      - master key
      - none
    value: ""
  validations:
    required: true

## Steps to reproduce

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: A clear and concise list of steps that can reproduce the bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    value: ""
  validations:
    required: true

## Describe what you expected to happen

- type: textarea
  id: expected-behavior
  attributes:
    label: Describe what you expected to happen
    description: A clear and concise description of what you expected to happen.
    placeholder: Tell us what should happen instead!
    value: ""
  validations:
    required:true

## Logfile

<!-- Please attach a debug log. Issues without a debug log are likely to stall. For information on how to collect a log file see https://joplinapp.org/debugging/ -->

- type : file 
   id : logfile 
   attributes :
     label : Logfile 
     description : The debug log file generated by Joplin.
     accept : .log,.txt 
     value : ""
   validations :
     required : false 

## Code of Conduct

- type : checkboxes 
   id : coc 
   attributes :
     label : Code of Conduct 
     description : By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/laurent22/joplin/blob/dev/CODE_OF_CONDUCT.md) 
     options :
       - label : "I agree to follow this project's Code of Conduct" 
         required : true 
         value : false
