name: "Bug Report"
title: "[Bug]: " 
labels: bug
assignees: octocat

body:
- type: input
  id: joplin-version
  attributes:
    label: Joplin version
    description: The version of Joplin you are using.
    placeholder: ex. 2.6.10
  validations:
    required: true

- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: The platform you are using Joplin on.
    options:
      - macOS
      - Linux
      - Windows
      - Android
      - iOS
      - terminal
  validations:
    required: true

- type: input
  id: os-specifics
  attributes:
    label: OS specifics
    description: The OS version, Linux distribution, Android/iOS version, etc.
    placeholder: ex. Windows 10, Ubuntu 20.04, Android 11
  validations:
    required: true

- type: dropdown
  id: sync-target
  attributes:
    label: Sync target
    description: The service you are using to sync your notes.
    options:
      - Dropbox
      - OneDrive
      - Nextcloud
      - WebDAV
      - File system
      - Joplin Server
  validations:
    required: true

- type: dropdown
  id: encryption-method
  attributes:
    label: Encryption method
    description: The method you are using to encrypt your notes.
    options:
      - E2EE
      - master key
      - nonencrypted
  validations:
    required: true

## Steps to reproduce

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: A clear and concise list of steps that can reproduce the bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

## Describe what you expected to happen

- type: textarea
  id: expected-behavior
  attributes:
    label: Describe what you expected to happen
    description: A clear and concise description of what you expected to happen.
    placeholder: Tell us what should happen instead!
  validations:
    required: true

